CREATE SCHEMA IF NOT EXISTS ot_shequguanli;

CREATE TABLE IF NOT EXISTS ot_shequguanli.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (role, username)
);

CREATE TABLE IF NOT EXISTS ot_shequguanli.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  status TEXT,
  owner TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT,
  extra JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO ot_shequguanli.accounts (id, role, username, password, display_name) VALUES
  (1, 'admin', 'abo', 'abo', '平台管理员'),
  (2, 'user', '张三', '123456', '社区业主'),
  (3, 'staff', '物业01', '123456', '物业人员')
ON CONFLICT (role, username) DO UPDATE SET
  password = EXCLUDED.password,
  display_name = EXCLUDED.display_name;

INSERT INTO ot_shequguanli.items (id, module_key, title, subtitle, status, owner, amount, description, extra) VALUES
  (1, 'owner', '业主信息演示记录1', '业主账号、房号、联系方式和入住状态', '进行中', '平台管理员', 10, '社区物业管理平台的业主信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (2, 'owner', '业主信息演示记录2', '业主账号、房号、联系方式和入住状态', '待处理', '社区业主', 20, '社区物业管理平台的业主信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (3, 'owner', '业主信息演示记录3', '业主账号、房号、联系方式和入住状态', '已完成', '物业人员', 30, '社区物业管理平台的业主信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (4, 'building', '楼房信息演示记录1', '楼栋、单元、房屋和社区区域', '进行中', '平台管理员', 10, '社区物业管理平台的楼房信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (5, 'building', '楼房信息演示记录2', '楼栋、单元、房屋和社区区域', '待处理', '社区业主', 20, '社区物业管理平台的楼房信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (6, 'building', '楼房信息演示记录3', '楼栋、单元、房屋和社区区域', '已完成', '物业人员', 30, '社区物业管理平台的楼房信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (7, 'parking', '车位信息演示记录1', '车位编号、类别、价格和预订状态', '进行中', '平台管理员', 10, '社区物业管理平台的车位信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (8, 'parking', '车位信息演示记录2', '车位编号、类别、价格和预订状态', '待处理', '社区业主', 20, '社区物业管理平台的车位信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (9, 'parking', '车位信息演示记录3', '车位编号、类别、价格和预订状态', '已完成', '物业人员', 30, '社区物业管理平台的车位信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (10, 'fee', '费用信息演示记录1', '物业费、水电费、缴费状态和金额', '进行中', '平台管理员', 10, '社区物业管理平台的费用信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (11, 'fee', '费用信息演示记录2', '物业费、水电费、缴费状态和金额', '待处理', '社区业主', 20, '社区物业管理平台的费用信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (12, 'fee', '费用信息演示记录3', '物业费、水电费、缴费状态和金额', '已完成', '物业人员', 30, '社区物业管理平台的费用信息模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (13, 'visitor', '访客管理演示记录1', '访客登记、来访事由和放行状态', '进行中', '平台管理员', 10, '社区物业管理平台的访客管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (14, 'visitor', '访客管理演示记录2', '访客登记、来访事由和放行状态', '待处理', '社区业主', 20, '社区物业管理平台的访客管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (15, 'visitor', '访客管理演示记录3', '访客登记、来访事由和放行状态', '已完成', '物业人员', 30, '社区物业管理平台的访客管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (16, 'notice', '社区公告演示记录1', '公告、留言、统计和社区资讯', '进行中', '平台管理员', 10, '社区物业管理平台的社区公告模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (17, 'notice', '社区公告演示记录2', '公告、留言、统计和社区资讯', '待处理', '社区业主', 20, '社区物业管理平台的社区公告模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (18, 'notice', '社区公告演示记录3', '公告、留言、统计和社区资讯', '已完成', '物业人员', 30, '社区物业管理平台的社区公告模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  module_key = EXCLUDED.module_key,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  status = EXCLUDED.status,
  owner = EXCLUDED.owner,
  amount = EXCLUDED.amount,
  description = EXCLUDED.description,
  extra = EXCLUDED.extra,
  updated_at = now();

SELECT setval(pg_get_serial_sequence('ot_shequguanli.accounts', 'id'), COALESCE((SELECT MAX(id) FROM ot_shequguanli.accounts), 1), true);
SELECT setval(pg_get_serial_sequence('ot_shequguanli.items', 'id'), COALESCE((SELECT MAX(id) FROM ot_shequguanli.items), 1), true);

CREATE OR REPLACE FUNCTION public.ot_shequguanli_demo_rest(
  p_table_name TEXT,
  p_method TEXT DEFAULT 'GET',
  p_query JSONB DEFAULT '{}'::jsonb,
  p_payload JSONB DEFAULT '{}'::jsonb
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_schema CONSTANT TEXT := 'ot_shequguanli';
  v_table TEXT;
  v_sql TEXT;
  v_rows JSONB := '[]'::jsonb;
  v_key TEXT;
  v_value TEXT;
  v_where TEXT := '';
  v_order TEXT := '';
  v_limit TEXT := '';
  v_set TEXT := '';
  v_columns TEXT := '';
  v_values TEXT := '';
BEGIN
  IF p_table_name NOT IN ('accounts', 'items') THEN
    RAISE EXCEPTION 'table is not allowed: %', p_table_name;
  END IF;

  v_table := format('%I.%I', v_schema, p_table_name);

  FOR v_key, v_value IN SELECT key, value #>> '{}' FROM jsonb_each(p_query)
  LOOP
    IF v_key = 'select' THEN
      CONTINUE;
    ELSIF v_key = 'order' THEN
      v_order := ' ORDER BY ' || quote_ident(split_part(v_value, '.', 1)) ||
        CASE WHEN lower(split_part(v_value, '.', 2)) = 'desc' THEN ' DESC' ELSE ' ASC' END;
    ELSIF v_key = 'limit' THEN
      v_limit := ' LIMIT ' || LEAST(GREATEST(v_value::int, 1), 200);
    ELSIF v_value LIKE 'eq.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' = ' || quote_literal(substring(v_value FROM 4));
    ELSIF v_value LIKE 'ilike.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' ILIKE ' || quote_literal(substring(v_value FROM 7));
    END IF;
  END LOOP;

  IF upper(p_method) = 'GET' THEN
    v_sql := 'SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM (SELECT * FROM ' || v_table || v_where || v_order || v_limit || ') t';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'POST' THEN
    SELECT string_agg(quote_ident(key), ', '), string_agg(quote_literal(value #>> '{}'), ', ')
      INTO v_columns, v_values
    FROM jsonb_each(p_payload)
    WHERE key <> 'id';
    IF v_columns IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'INSERT INTO ' || v_table || ' (' || v_columns || ') VALUES (' || v_values || ') RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'PATCH' THEN
    SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value #>> '{}'), ', ')
      INTO v_set
    FROM jsonb_each(p_payload)
    WHERE key <> 'id' AND key <> 'created_at';
    IF v_set IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'UPDATE ' || v_table || ' SET ' || v_set || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'DELETE' THEN
    v_sql := 'DELETE FROM ' || v_table || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  END IF;

  RAISE EXCEPTION 'method is not allowed: %', p_method;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ot_shequguanli_demo_rest(TEXT, TEXT, JSONB, JSONB) TO anon, authenticated, service_role;
